<?php  
register_post_type('crb_gallery', array(
	'labels' => array(
		'name'	 => __('Gallery', 'crb'),
		'singular_name' => __('Gallery Item', 'crb'),
		'add_new' => __('Add New', 'crb'),
		'add_new_item' => __('Add new Gallery Item', 'crb'),
		'view_item' => __('View Gallery Item', 'crb'),
		'edit_item' => __('Edit Gallery Item', 'crb'),
		'new_item' => __('New Gallery Item', 'crb'),
		'view_item' => __('View Gallery Item', 'crb'),
		'search_items' => __('Search Gallery', 'crb'),
		'not_found' =>  __('No Gallery found', 'crb'),
		'not_found_in_trash' => __('No Gallery found in trash', 'crb'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'menu_icon' => 'dashicons-images-alt',
	'menu_position' => 20,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'taxonomies' => array('category'),
	'query_var' => true,
	'supports' => array('title', 'thumbnail', 'page-attributes'),
));

register_post_type('crb_home_slider', array(
	'labels' => array(
		'name'	 => __('Home Slider', 'crb'),
		'singular_name' => __('Home Slide', 'crb'),
		'add_new' => __('Add New', 'crb'),
		'add_new_item' => __('Add new Home Slide', 'crb'),
		'view_item' => __('View Home Slide', 'crb'),
		'edit_item' => __('Edit Home Slide', 'crb'),
		'new_item' => __('New Home Slide', 'crb'),
		'view_item' => __('View Home Slide', 'crb'),
		'search_items' => __('Search Home Slider', 'crb'),
		'not_found' =>  __('No Home Slider found', 'crb'),
		'not_found_in_trash' => __('No Home Slider found in trash', 'crb'),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'menu_icon' => 'dashicons-images-alt2',
	'menu_position' => 20,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' =>  'post.php?post=%d',
	'query_var' => true,
	'supports' => array('title', 'page-attributes'),
));
